/**
 * Source-image ceiling.
 *
 * Every image that becomes part of an ad — whether uploaded by the customer,
 * pulled from Pixabay, or generated by AI — must end up a valid raster under
 * 150 KB. This is the ONE place that guarantees it, so no ingest path can
 * forget the rule.
 *
 * The guarantee is not "reject if too big" but "make it fit": a 4 MB phone
 * photo is downscaled and re-encoded until it is under budget, because
 * rejecting a customer's only photo helps no one. Only genuinely unusable
 * input (not an image, zero bytes) is refused.
 *
 * 150 KB is the source budget the brief specified. It is deliberately below
 * Google's 150 KB *delivered-creative* limit too, so a hero image can never
 * be the reason a finished ad blows its platform ceiling.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import sharp from 'sharp';

export const MAX_IMAGE_BYTES = 150 * 1024;

export interface FitResult {
  /** Path to the written, under-budget image. */
  file: string;
  bytes: number;
  width: number;
  height: number;
  format: string;
  /** True if the image had to be compressed or downscaled to fit. */
  reencoded: boolean;
  /** Human note when something was done to the file, for surfacing in the UI. */
  note?: string;
}

/**
 * Take an image (buffer or path), guarantee it is a valid raster under
 * MAX_IMAGE_BYTES, and write it to `outFile`. Throws only if the input is not
 * a usable image at all.
 *
 * `keepAlpha` preserves transparency (for logos); heroes and backgrounds are
 * flattened to JPEG, which compresses photographs far smaller than PNG.
 */
export async function fitImageToBudget(
  input: Buffer | string,
  outFile: string,
  opts: { keepAlpha?: boolean; maxDimension?: number } = {},
): Promise<FitResult> {
  let img = sharp(input, { failOn: 'error' });
  let meta;
  try {
    meta = await img.metadata();
  } catch {
    throw new Error('That file is not a readable image.');
  }
  if (!meta.width || !meta.height) throw new Error('That image has no dimensions — it may be corrupt.');

  fs.mkdirSync(path.dirname(outFile), { recursive: true });

  const keepAlpha = opts.keepAlpha ?? (meta.hasAlpha && meta.format === 'png');
  const maxDim = opts.maxDimension ?? 2000; // no source needs to exceed this for display ads

  // First pass: cap dimensions (a 6000px photo is pure waste for a 970px ad).
  let width = meta.width;
  let height = meta.height;
  if (Math.max(width, height) > maxDim) {
    const s = maxDim / Math.max(width, height);
    width = Math.round(width * s);
    height = Math.round(height * s);
  }

  async function encode(w: number, h: number, quality: number): Promise<Buffer> {
    const pipe = sharp(input).resize({ width: w, height: h, fit: 'inside', withoutEnlargement: true });
    return keepAlpha
      ? pipe.png({ compressionLevel: 9, quality }).toBuffer()
      : pipe.flatten({ background: '#ffffff' }).jpeg({ quality, mozjpeg: true }).toBuffer();
  }

  // Try progressively harder: drop quality, then dimensions, until under budget.
  let buf = await encode(width, height, 82);
  let reencoded = buf.length !== (typeof input === 'string' ? fs.statSync(input).size : input.length);
  let quality = 82;
  let guard = 0;
  while (buf.length > MAX_IMAGE_BYTES && guard++ < 12) {
    reencoded = true;
    if (quality > 40) {
      quality -= 12;
    } else {
      // Quality is as low as we'll go; shrink dimensions 15% and reset quality.
      width = Math.round(width * 0.85);
      height = Math.round(height * 0.85);
      quality = 70;
    }
    buf = await encode(width, height, quality);
  }

  if (buf.length > MAX_IMAGE_BYTES) {
    throw new Error('Could not compress this image under 150 KB — please use a simpler or smaller image.');
  }

  const finalMeta = await sharp(buf).metadata();
  fs.writeFileSync(outFile, buf);

  const originalBytes = typeof input === 'string' ? fs.statSync(input).size : input.length;
  return {
    file: outFile,
    bytes: buf.length,
    width: finalMeta.width ?? width,
    height: finalMeta.height ?? height,
    format: keepAlpha ? 'png' : 'jpg',
    reencoded,
    note: reencoded
      ? `Optimized from ${(originalBytes / 1024).toFixed(0)} KB to ${(buf.length / 1024).toFixed(0)} KB to meet the 150 KB limit.`
      : undefined,
  };
}
